
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\mrshu\reps\Tkinter-Designer\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("804x549")
window.configure(bg = "#121212")


canvas = Canvas(
    window,
    bg = "#121212",
    height = 549,
    width = 804,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    89.0,
    100.0,
    722.0,
    403.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    503.0,
    340.0,
    1164.0,
    1001.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    742.0,
    15.0,
    788.0,
    52.0,
    fill="#000000",
    outline="")

canvas.create_text(
    15.0,
    15.0,
    anchor="nw",
    text="StylePerformer",
    fill="#FFFFFF",
    font=("RalewayRoman Regular", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
